export const products = [
  {
    id: 1,
    name: 'Solar System Discovery Kit',
    price: 45.99,
    description: 'Interactive solar system model with STEM learning guide.',
    image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=600',
    category: 'Educational',
    rating: 4.8,
    age_range: '6-8',
    best_seller: 1,
    new_arrival: 0,
  },
  {
    id: 2,
    name: 'Magnetic Building Tiles',
    price: 34.5,
    description: '50-piece 3D magnetic building set for creative construction.',
    image: 'https://images.unsplash.com/photo-1543269664-56d93c1b41a6?auto=format&fit=crop&q=80&w=600',
    category: 'STEM',
    rating: 4.9,
    age_range: '3-5',
    best_seller: 0,
    new_arrival: 1,
  },
  {
    id: 3,
    name: 'Eco-Friendly Teddy Bear',
    price: 22,
    description: 'Hand-stitched plush bear made from 100% recycled materials.',
    image: 'https://images.unsplash.com/photo-1559440666-4477c288d8db?auto=format&fit=crop&q=80&w=600',
    category: 'Soft Toys',
    rating: 5,
    age_range: '0-2',
    best_seller: 1,
    new_arrival: 0,
  },
  {
    id: 4,
    name: 'Giant Plush Dinosaur',
    price: 55,
    description: 'Soft and cuddly dinosaur friend for endless hugs.',
    image: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?auto=format&fit=crop&q=80&w=600',
    category: 'Soft Toys',
    rating: 4.7,
    age_range: '3-5',
    best_seller: 0,
    new_arrival: 1,
  },
  {
    id: 5,
    name: 'Coding Caterpillar',
    price: 49,
    description: 'Learn basic coding logic with this interactive musical caterpillar.',
    image: 'https://images.unsplash.com/photo-1531210609132-5d7ad3109a1c?auto=format&fit=crop&q=80&w=600',
    category: 'STEM',
    rating: 4.8,
    age_range: '3-5',
    best_seller: 1,
    new_arrival: 0,
  },
  {
    id: 6,
    name: 'Junior Microscope Set',
    price: 29.99,
    description: 'Beginner microscope with 10 slides and experiment manual.',
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&q=80&w=600',
    category: 'Educational',
    rating: 4.6,
    age_range: '6-8',
    best_seller: 0,
    new_arrival: 1,
  },
  {
    id: 7,
    name: 'Explorer Backyard Tent',
    price: 39.99,
    description: 'Pop-up tent for outdoor adventures and indoor hideouts.',
    image: 'https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?auto=format&fit=crop&q=80&w=600',
    category: 'Outdoor',
    rating: 4.9,
    age_range: '3-5',
    best_seller: 1,
    new_arrival: 0,
  },
];

export default products;
